# Site settings
title: Archive
description: Press articles, mentions and other accomplishments throughout my life.
baseurl: "/archive"
url: "https://kike.wtf"
author: Kike Fontán
email: hola@kike.wtf
plugins: [jekyll-feed]
# Build settings
highlighter: null
markdown: kramdown